name: Build HzO Titan APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer Flet
        run: |
          pip install flet telepot

      - name: Fabriquer l'APK
        run: |
          flet build apk

      - name: Sauvegarder l'APK
        uses: actions/upload-artifact@v4
        with:
          name: hzo-titan-app
          path: build/apk/*.apk
          
